version: '3.8'

services:
  db:
    image: postgres
    ports:
      -"5433:5432"
    environment:
      - POSTGRES_PASSWORD=admin123
      - POSTGRES_DB:UserTask
  app:
    image: openjdk:17-jdk-slim
    container_name: java17-app
    working_dir: /app
    volumes:
      - .:/app
    command: ["java", "-version"]