spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/UserTask
    username: UserTask
    password: admin123
    name: UserTask
  jpa:
    hibernate: ddl:auto:update

sql:
  init: mode:always
    schema-locations:classpath:/schema.sql
springdoc:
  api-doc:
    enabled: true
  swagger-ui:
    path: /swagger-ui.html
  group-confligs:
    - group: project-pmanagement
      path-to-match: /api/pmanagement/**
